apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi