apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-hpa
spec:
  maxReplicas: 100 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  targetCPUUtilizationPercentage: 50 # target CPU utilization

